package:
  namespace: devices
  name: tmc2209
  version: 2.1.0
  kind: device

device:
  class: stepper_driver
  model: tmc2209

requires:
  connector: stepper_driver_socket

dependencies:
  chips/generic-mcu:
    version: ">=1.2,<2.0"

capabilities:
  - stepper.drive
  - stepper.uart_config
